[Test]: Test new action flow

diff --git a/.github/workflows/gh-page-deploy.yml b/.github/workflows/gh-page-deploy.yml
--- a/.github/workflows/gh-page-deploy.yml
+++ b/.github/workflows/gh-page-deploy.yml
@@ -6,35 +6,41 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     steps:
     - name: Clone Repository
       run: |
         git clone --branch main --depth 1 https://github.com/humtej1204/NextJs-Portafolio_Page.git repo
 
-    - name: Detect package manager
-      id: detect-package-manager
-      run: |
-        if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-          echo "manager=yarn" >> $GITHUB_OUTPUT
-          echo "command=install" >> $GITHUB_OUTPUT
-          echo "runner=yarn" >> $GITHUB_OUTPUT
-          exit 0
-        elif [ -f "${{ github.workspace }}/package.json" ]; then
-          echo "manager=npm" >> $GITHUB_OUTPUT
-          echo "command=ci" >> $GITHUB_OUTPUT
-          echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-          exit 0
-        else
-          echo "Unable to determine package manager"
-          exit 1
-        fi
+    # - name: Detect package manager
+    #   id: detect-package-manager
+    #   run: |
+    #     if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+    #       echo "manager=yarn" >> $GITHUB_OUTPUT
+    #       echo "command=install" >> $GITHUB_OUTPUT
+    #       echo "runner=yarn" >> $GITHUB_OUTPUT
+    #       exit 0
+    #     elif [ -f "${{ github.workspace }}/package.json" ]; then
+    #       echo "manager=npm" >> $GITHUB_OUTPUT
+    #       echo "command=ci" >> $GITHUB_OUTPUT
+    #       echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+    #       exit 0
+    #     else
+    #       echo "Unable to determine package manager"
+    #       exit 1
+    #     fi
 
     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 20
+
+    # - name: Install dependencies
+    #   run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
+    # - name: Build with Next.js
+    #   run: ${{ steps.detect-package-manager.outputs.runner }} next build
 
     - name: Setup Pages
       run: mkdir -p $GITHUB_WORKSPACE/.github && echo "{}" > $GITHUB_WORKSPACE/.github/pages.json
@@ -47,10 +53,10 @@ jobs:
         fi
 
     - name: Install dependencies
-      run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      run: npm install
 
     - name: Build with Next.js
-      run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      run: npm install run build
 
     - name: Save cache
       run: |
